language: php

# We use trusty as currently there is an issue with java and moodle-plugin-ci mustache linting which
# causes causes tests to fail on xenial and bionic. (See https://github.com/blackboard-open-source/moodle-plugin-ci/issues/91).
dist: trusty

addons:
  firefox: latest
  chrome: stable
  postgresql: "9.6"
  packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
env:
  global:
    - MOODLE_BRANCH=master
    - IGNORE_PATHS=tests/fixtures
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=pgsql MOODLE_BRANCH=master
    - DB=mysqli MOODLE_BRANCH=master

dist: trusty

matrix:
  exclude:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
  - sudo apt-get update
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat